import type { Metadata } from "next";
import { Bar } from "@/components/Bar/Bar";
import { NavBar } from "@/components/NavBar/NavBar";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import styles from "./layout.module.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function TrackLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.wrapper}>
      <div className={styles.container}>
        <main className={styles.main} >
          <NavBar />
          {children}
          <Sidebar />
        </main>
        <Bar />
        <footer className="footer"></footer>
      </div>
    </div>
  );
}