import type { Metadata } from "next";
//import localFont from "next/font/local";
import "./globals.css";

import { Montserrat } from 'next/font/google'
import ReduxProvider from "@/store/ReduxProvider";

const montserrat = Montserrat({subsets: ["cyrillic"]})


// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <ReduxProvider>
      <body className={montserrat.className}>
        {children}
      </body>
      </ReduxProvider>
    </html>
  );
}
